/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PermissionsSkeleton: typeof import('./src/components/system/users/PermissionsSkeleton.vue')['default']
    RolePermissionsDialog: typeof import('./src/components/system/roles/RolePermissionsDialog.vue')['default']
    RolesStats: typeof import('./src/components/system/roles/RolesStats.vue')['default']
    RolesTable: typeof import('./src/components/system/roles/RolesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserDetailsDialog: typeof import('./src/components/system/users/UserDetailsDialog.vue')['default']
    UserEditDialog: typeof import('./src/components/system/users/UserEditDialog.vue')['default']
    UserPermissionsDialog: typeof import('./src/components/system/users/UserPermissionsDialog.vue')['default']
    UsersFilters: typeof import('./src/components/system/users/UsersFilters.vue')['default']
    UsersStats: typeof import('./src/components/system/users/UsersStats.vue')['default']
    UsersTable: typeof import('./src/components/system/users/UsersTable.vue')['default']
    UsersTableSkeleton: typeof import('./src/components/system/users/UsersTableSkeleton.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
