/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActualiteCard: typeof import('./src/components/ActualiteCard.vue')['default']
    ActualiteCreateDialog: typeof import('./src/components/actualites/ActualiteCreateDialog.vue')['default']
    ActualiteDeleteDialog: typeof import('./src/components/actualites/ActualiteDeleteDialog.vue')['default']
    ActualiteDetailsDialog: typeof import('./src/components/actualites/ActualiteDetailsDialog.vue')['default']
    ActualiteEditDialog: typeof import('./src/components/actualites/ActualiteEditDialog.vue')['default']
    AddUserDialog: typeof import('./src/components/users/AddUserDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CreateDialog: typeof import('./src/components/actualites/CreateDialog.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GlobalSearch: typeof import('./src/components/GlobalSearch.vue')['default']
    GlobalSearchModal: typeof import('./src/components/GlobalSearchModal.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NotificationDropdown: typeof import('./src/components/NotificationDropdown.vue')['default']
    NotificationToast: typeof import('./src/components/NotificationToast.vue')['default']
    PermissionsSkeleton: typeof import('./src/components/system/users/PermissionsSkeleton.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RichTextEditorFixed: typeof import('./src/components/RichTextEditorFixed.vue')['default']
    RichTextEditorSimple: typeof import('./src/components/RichTextEditorSimple.vue')['default']
    RolePermissionsDialog: typeof import('./src/components/system/roles/RolePermissionsDialog.vue')['default']
    RolesStats: typeof import('./src/components/system/roles/RolesStats.vue')['default']
    RolesTable: typeof import('./src/components/system/roles/RolesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestModal: typeof import('./src/components/TestModal.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserCreateDialog: typeof import('./src/components/system/users/UserCreateDialog.vue')['default']
    UserDetailsDialog: typeof import('./src/components/system/users/UserDetailsDialog.vue')['default']
    UserEditDialog: typeof import('./src/components/system/users/UserEditDialog.vue')['default']
    UserPermissionsDialog: typeof import('./src/components/system/users/UserPermissionsDialog.vue')['default']
    UsersFilters: typeof import('./src/components/system/users/UsersFilters.vue')['default']
    UsersStats: typeof import('./src/components/system/users/UsersStats.vue')['default']
    UsersTable: typeof import('./src/components/system/users/UsersTable.vue')['default']
    UsersTableSkeleton: typeof import('./src/components/system/users/UsersTableSkeleton.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
