version: '3.8'

services:
  lafaom-mao-institut:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - lafaom-mao-network

networks:
  lafaom-mao-network:
    driver: bridge 
